/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attribute: typeof import('./src/components/TopoEditor/Attribute/index.vue')['default']
    AttributeTrigger: typeof import('./src/components/TopoEditor/Panel/Right/Attribute/AttributeTrigger.vue')['default']
    copy: typeof import('./src/components/TopoEditor/Panel/Left/LayerList copy.vue')['default']
    Editor: typeof import('./src/components/TopoEditor/Editor/index.vue')['default']
    Header: typeof import('./src/components/TopoEditor/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Layer: typeof import('./src/components/TopoEditor/Panel/Left/Layer.vue')['default']
    LayerList: typeof import('./src/components/TopoEditor/Panel/Left/LayerList.vue')['default']
    Left: typeof import('./src/components/TopoEditor/Panel/Left/index.vue')['default']
    LeftPanel: typeof import('./src/components/TopoEditor/Panel/LeftPanel.vue')['default']
    LinkAttribute: typeof import('./src/components/TopoEditor/Panel/Right/Attribute/LinkAttribute.vue')['default']
    MapAttribute: typeof import('./src/components/TopoEditor/Panel/Right/Attribute/MapAttribute.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NodeAttribute: typeof import('./src/components/TopoEditor/Panel/Right/Attribute/NodeAttribute.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTree: typeof import('naive-ui')['NTree']
    NUpload: typeof import('naive-ui')['NUpload']
    Panel: typeof import('./src/components/TopoEditor/Common/Panel/index.vue')['default']
    RightPanel: typeof import('./src/components/TopoEditor/Panel/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/TopoEditor/Sider/index.vue')['default']
    TabPane: typeof import('./src/components/TopoEditor/Panel/Left/TabPane.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopoEditor: typeof import('./src/components/TopoEditor/index.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
